// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDVZk7H1dW2nMg4-R8DxleSJXMag83_BCM',
    appId: '1:291698501941:web:e31e66470d0938b120847c',
    messagingSenderId: '291698501941',
    projectId: 'sketchbot-app',
    authDomain: 'sketchbot-app.firebaseapp.com',
    storageBucket: 'sketchbot-app.firebasestorage.app',
    measurementId: 'G-GV9JLX8KXK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwKlhfHZGr-tqpe4HdGtxe-sNhp2P9M7g',
    appId: '1:291698501941:android:ad037504c9e6ca2220847c',
    messagingSenderId: '291698501941',
    projectId: 'sketchbot-app',
    storageBucket: 'sketchbot-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq6rYpBzw9M-9e4E_taGT-KRw3bXJ2ubk',
    appId: '1:291698501941:ios:bcbdc5008a4efc9920847c',
    messagingSenderId: '291698501941',
    projectId: 'sketchbot-app',
    storageBucket: 'sketchbot-app.firebasestorage.app',
    iosBundleId: 'com.example.sketchbotSimulator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAq6rYpBzw9M-9e4E_taGT-KRw3bXJ2ubk',
    appId: '1:291698501941:ios:bcbdc5008a4efc9920847c',
    messagingSenderId: '291698501941',
    projectId: 'sketchbot-app',
    storageBucket: 'sketchbot-app.firebasestorage.app',
    iosBundleId: 'com.example.sketchbotSimulator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDVZk7H1dW2nMg4-R8DxleSJXMag83_BCM',
    appId: '1:291698501941:web:795d53d595bc844320847c',
    messagingSenderId: '291698501941',
    projectId: 'sketchbot-app',
    authDomain: 'sketchbot-app.firebaseapp.com',
    storageBucket: 'sketchbot-app.firebasestorage.app',
    measurementId: 'G-15TT6E3E2Z',
  );
}
